server {
    listen 80;

    # Tutte le richieste alla root passano al webapp Apache
    location / {
        proxy_pass http://webapp:80;
    }

    # /auth → se volessi backend separato per login
    location /auth {
        proxy_pass http://auth:9091;
    }

    # Gzip per cartelle Build (WebGL)
    location /Build {
        gzip_static on;
    }
}
